version: '3.8'

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - database-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - postgres
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - '5050:80'
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 2G
        networks:
            - postgres

networks:
    postgres:
        driver: bridge
volumes:
    database-data:
    pgadmin:
